spring:
  datasource:
    url: jdbc:h2:mem:home_video_log;MODE=MYSQL
  h2:
    console:
      enabled: true
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always
      
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
         expiration: 604800000 # 7 days
         
spring-doc:
   swagger-ui:
      tagsSorter: alpha
      
# Commented out the logging section
# logging:
#   level:
#     root: DEBUG
         